import './EdaReport.css'

function EdaReport({ reportUrl }) {
    if (!reportUrl) return null

    // The report is served via the backend at /api/reports/...
    const fullUrl = `/api${reportUrl}`

    return (
        <div className="eda-report-container">
            <h2>📊 EDA Report</h2>
            <p className="eda-subtitle">
                Interactive data profiling report generated by ydata-profiling
            </p>
            <div className="eda-iframe-wrapper">
                <iframe
                    src={fullUrl}
                    title="EDA Report"
                    className="eda-iframe"
                    sandbox="allow-scripts allow-same-origin"
                />
            </div>
            <a href={fullUrl} target="_blank" rel="noopener noreferrer" className="eda-open-link">
                Open in new tab ↗
            </a>
        </div>
    )
}

export default EdaReport
