function EdaReport({ reportUrl }) {
    if (!reportUrl) return null

    const fullUrl = `/api${reportUrl}`

    return (
        <div className="max-w-4xl mx-auto mt-8 px-4 text-center">
            <h2 className="text-2xl font-bold bg-gradient-to-r from-emerald-400 to-blue-500 bg-clip-text text-transparent">
                📊 EDA Report
            </h2>
            <p className="text-gray-500 text-sm mb-4">
                Interactive data profiling report generated by ydata-profiling
            </p>

            <div className="rounded-xl overflow-hidden border border-white/10 bg-white">
                <iframe
                    src={fullUrl}
                    title="EDA Report"
                    className="w-full h-[600px] border-none"
                    sandbox="allow-scripts allow-same-origin"
                />
            </div>

            <a
                href={fullUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-block mt-3 text-sm text-indigo-400 hover:text-indigo-300 hover:underline transition-colors"
            >
                Open in new tab ↗
            </a>
        </div>
    )
}

export default EdaReport
